################################################################################
# Automatically-generated file. Do not edit!
################################################################################

ASM_UPPER_SRCS := 
O_SRCS := 
ELF_SRCS := 
SX_SRCS := 
LINKER_SCRIPT := 
JMP_UPPER_SRCS := 
P_UPPER_SRCS := 
SRC_SRCS := 
JMP_SRCS := 
FSY_UPPER_SRCS := 
PP_UPPER_SRCS := 
OBJ_UPPER_SRCS := 
ASM_SRCS := 
SX_UPPER_SRCS := 
O_UPPER_SRCS := 
S_UPPER_SRCS := 
ELF_UPPER_SRCS := 
C_UPPER_SRCS := 
OBJ_SRCS := 
S_SRCS := 
PP_SRCS := 
SRC_UPPER_SRCS := 
FSY_SRCS := 
P_SRCS := 
C_SRCS := 
JMP_DEPS := 
FSY_DEPS := 
C_UPPER_DEPS := 
SECONDARY_SIZE := 
SRC_UPPER_DEPS := 
P_UPPER_DEPS := 
S_DEPS := 
PP_UPPER_DEPS := 
P_DEPS := 
FSY_UPPER_DEPS := 
C_DEPS := 
SRC_DEPS := 
JMP_UPPER_DEPS := 
PP_DEPS := 
SX_DEPS := 
ASM_UPPER_DEPS := 
SX_UPPER_DEPS := 
OBJS := 
SECONDARY_FLASH := 
ASM_DEPS := 
SREC := 
S_UPPER_DEPS := 
MAP := 

# Every subdirectory with source files must be described here
SUBDIRS := \
Application \
mtk3_bsp2/etc/linker \
mtk3_bsp2/mtkernel/device/adc \
mtk3_bsp2/mtkernel/device/adc/sysdepend/rx231 \
mtk3_bsp2/mtkernel/device/adc/sysdepend/rx65n \
mtk3_bsp2/mtkernel/device/adc/sysdepend/rza2m \
mtk3_bsp2/mtkernel/device/adc/sysdepend/stm32h7 \
mtk3_bsp2/mtkernel/device/adc/sysdepend/stm32l4 \
mtk3_bsp2/mtkernel/device/adc/sysdepend/tx03_m367 \
mtk3_bsp2/mtkernel/device/common/drvif \
mtk3_bsp2/mtkernel/device/i2c \
mtk3_bsp2/mtkernel/device/i2c/sysdepend/rx231 \
mtk3_bsp2/mtkernel/device/i2c/sysdepend/rx65n \
mtk3_bsp2/mtkernel/device/i2c/sysdepend/rza2m \
mtk3_bsp2/mtkernel/device/i2c/sysdepend/stm32h7 \
mtk3_bsp2/mtkernel/device/i2c/sysdepend/stm32l4 \
mtk3_bsp2/mtkernel/device/i2c/sysdepend/tx03_m367 \
mtk3_bsp2/mtkernel/device/ser \
mtk3_bsp2/mtkernel/device/ser/sysdepend/rx231 \
mtk3_bsp2/mtkernel/device/ser/sysdepend/rx65n \
mtk3_bsp2/mtkernel/device/ser/sysdepend/rza2m \
mtk3_bsp2/mtkernel/device/ser/sysdepend/stm32h7 \
mtk3_bsp2/mtkernel/device/ser/sysdepend/stm32l4 \
mtk3_bsp2/mtkernel/device/ser/sysdepend/tx03_m367 \
mtk3_bsp2/mtkernel/etc/linker/iote_m367 \
mtk3_bsp2/mtkernel/etc/linker/iote_rx231 \
mtk3_bsp2/mtkernel/etc/linker/iote_rza2m \
mtk3_bsp2/mtkernel/etc/linker/iote_stm32l4 \
mtk3_bsp2/mtkernel/kernel/inittask \
mtk3_bsp2/mtkernel/kernel/sysdepend/cpu/core/armv7a \
mtk3_bsp2/mtkernel/kernel/sysdepend/cpu/core/armv7m \
mtk3_bsp2/mtkernel/kernel/sysdepend/cpu/core/rxv2 \
mtk3_bsp2/mtkernel/kernel/sysdepend/cpu/rx231 \
mtk3_bsp2/mtkernel/kernel/sysdepend/cpu/rx65n \
mtk3_bsp2/mtkernel/kernel/sysdepend/cpu/rza2m \
mtk3_bsp2/mtkernel/kernel/sysdepend/cpu/stm32h7 \
mtk3_bsp2/mtkernel/kernel/sysdepend/cpu/stm32l4 \
mtk3_bsp2/mtkernel/kernel/sysdepend/cpu/tx03_m367 \
mtk3_bsp2/mtkernel/kernel/sysdepend/iote_m367 \
mtk3_bsp2/mtkernel/kernel/sysdepend/iote_rx231 \
mtk3_bsp2/mtkernel/kernel/sysdepend/iote_rza2m \
mtk3_bsp2/mtkernel/kernel/sysdepend/iote_stm32l4 \
mtk3_bsp2/mtkernel/kernel/sysinit \
mtk3_bsp2/mtkernel/kernel/tkernel \
mtk3_bsp2/mtkernel/kernel/tstdlib \
mtk3_bsp2/mtkernel/kernel/usermain \
mtk3_bsp2/mtkernel/lib/libtk \
mtk3_bsp2/mtkernel/lib/libtk/sysdepend/cpu/core/armv7a \
mtk3_bsp2/mtkernel/lib/libtk/sysdepend/cpu/core/armv7m \
mtk3_bsp2/mtkernel/lib/libtk/sysdepend/cpu/core/rxv2 \
mtk3_bsp2/mtkernel/lib/libtk/sysdepend/cpu/rx231 \
mtk3_bsp2/mtkernel/lib/libtk/sysdepend/cpu/rx65n \
mtk3_bsp2/mtkernel/lib/libtk/sysdepend/cpu/rza2m \
mtk3_bsp2/mtkernel/lib/libtk/sysdepend/cpu/stm32h7 \
mtk3_bsp2/mtkernel/lib/libtk/sysdepend/cpu/stm32l4 \
mtk3_bsp2/mtkernel/lib/libtk/sysdepend/cpu/tx03_m367 \
mtk3_bsp2/mtkernel/lib/libtm \
mtk3_bsp2/mtkernel/lib/libtm/sysdepend/iote_m367 \
mtk3_bsp2/mtkernel/lib/libtm/sysdepend/iote_rx231 \
mtk3_bsp2/mtkernel/lib/libtm/sysdepend/iote_rza2m \
mtk3_bsp2/mtkernel/lib/libtm/sysdepend/iote_stm32l4 \
mtk3_bsp2/mtkernel/lib/libtm/sysdepend/no_device \
mtk3_bsp2/sysdepend/nxp_mcux/cpu/core/armv8m \
mtk3_bsp2/sysdepend/nxp_mcux/device/hal_adc \
mtk3_bsp2/sysdepend/nxp_mcux/device/hal_lpi2c \
mtk3_bsp2/sysdepend/nxp_mcux \
mtk3_bsp2/sysdepend/nxp_mcux/lib/libtk/cpu/core/armv8m \
mtk3_bsp2/sysdepend/nxp_mcux/lib/libtm/evk_lpc55s69 \
mtk3_bsp2/sysdepend/nxp_mcux/lib/libtm/frdm_mcxn947 \
mtk3_bsp2/sysdepend/ra_fsp/cpu/core/armv7m \
mtk3_bsp2/sysdepend/ra_fsp/cpu/core/armv8m \
mtk3_bsp2/sysdepend/ra_fsp/device/hal_adc \
mtk3_bsp2/sysdepend/ra_fsp/device/hal_adhb \
mtk3_bsp2/sysdepend/ra_fsp/device/hal_i2c \
mtk3_bsp2/sysdepend/ra_fsp/device/hal_i3c_i2c \
mtk3_bsp2/sysdepend/ra_fsp/device/hal_sci_i2c \
mtk3_bsp2/sysdepend/ra_fsp \
mtk3_bsp2/sysdepend/ra_fsp/lib/libtk/cpu/core/armv7m \
mtk3_bsp2/sysdepend/ra_fsp/lib/libtk/cpu/core/armv8m \
mtk3_bsp2/sysdepend/ra_fsp/lib/libtm/arduino_unor4 \
mtk3_bsp2/sysdepend/ra_fsp/lib/libtm/clicker_ra4m1 \
mtk3_bsp2/sysdepend/ra_fsp/lib/libtm/ek_ra6m3 \
mtk3_bsp2/sysdepend/ra_fsp/lib/libtm/ek_ra8d1 \
mtk3_bsp2/sysdepend/ra_fsp/lib/libtm/ek_ra8m1 \
mtk3_bsp2/sysdepend/ra_fsp/lib/libtm/ek_ra8p1 \
mtk3_bsp2/sysdepend/ra_fsp/lib/libtm/fpb_ra4e1 \
mtk3_bsp2/sysdepend/stm32_cube/cpu/core/armv7m \
mtk3_bsp2/sysdepend/stm32_cube/cpu/core/armv8m \
mtk3_bsp2/sysdepend/stm32_cube/device/hal_adc \
mtk3_bsp2/sysdepend/stm32_cube/device/hal_adc/sysdepend \
mtk3_bsp2/sysdepend/stm32_cube/device/hal_i2c \
mtk3_bsp2/sysdepend/stm32_cube \
mtk3_bsp2/sysdepend/stm32_cube/lib/libtk/cpu/core/armv7m \
mtk3_bsp2/sysdepend/stm32_cube/lib/libtk/cpu/core/armv8m \
mtk3_bsp2/sysdepend/stm32_cube/lib/libtk/cpu/stm32f4 \
mtk3_bsp2/sysdepend/stm32_cube/lib/libtk/cpu/stm32f7 \
mtk3_bsp2/sysdepend/stm32_cube/lib/libtk/cpu/stm32g4 \
mtk3_bsp2/sysdepend/stm32_cube/lib/libtk/cpu/stm32h5 \
mtk3_bsp2/sysdepend/stm32_cube/lib/libtk/cpu/stm32h7 \
mtk3_bsp2/sysdepend/stm32_cube/lib/libtk/cpu/stm32l4 \
mtk3_bsp2/sysdepend/stm32_cube/lib/libtk/cpu/stm32n6 \
mtk3_bsp2/sysdepend/stm32_cube/lib/libtk \
mtk3_bsp2/sysdepend/stm32_cube/lib/libtm/discovery_stm32n657 \
mtk3_bsp2/sysdepend/stm32_cube/lib/libtm/nucleo_stm32f401 \
mtk3_bsp2/sysdepend/stm32_cube/lib/libtm/nucleo_stm32f411 \
mtk3_bsp2/sysdepend/stm32_cube/lib/libtm/nucleo_stm32f446 \
mtk3_bsp2/sysdepend/stm32_cube/lib/libtm/nucleo_stm32f767 \
mtk3_bsp2/sysdepend/stm32_cube/lib/libtm/nucleo_stm32g431 \
mtk3_bsp2/sysdepend/stm32_cube/lib/libtm/nucleo_stm32g491 \
mtk3_bsp2/sysdepend/stm32_cube/lib/libtm/nucleo_stm32h533 \
mtk3_bsp2/sysdepend/stm32_cube/lib/libtm/nucleo_stm32h723 \
mtk3_bsp2/sysdepend/stm32_cube/lib/libtm/nucleo_stm32l476 \
mtk3_bsp2/sysdepend/stm32_cube/lib/libtm/nucleo_stm32l4r5 \
mtk3_bsp2/sysdepend/xmc_mtb/cpu/core/armv7m \
mtk3_bsp2/sysdepend/xmc_mtb/cpu/xmc7200 \
mtk3_bsp2/sysdepend/xmc_mtb/device/hal_adc \
mtk3_bsp2/sysdepend/xmc_mtb/device/hal_adc/sysdepend/xmc7200 \
mtk3_bsp2/sysdepend/xmc_mtb/device/hal_i2c \
mtk3_bsp2/sysdepend/xmc_mtb/device/hal_i2c/sysdepend/xmc7200 \
mtk3_bsp2/sysdepend/xmc_mtb \
mtk3_bsp2/sysdepend/xmc_mtb/lib/libtk/cpu/core/armv7m \
mtk3_bsp2/sysdepend/xmc_mtb/lib/libtk/cpu/xmc7200 \
mtk3_bsp2/sysdepend/xmc_mtb/lib/libtm/evk_xmc7200 \
ra/arm/CMSIS-DSP/Source/BasicMathFunctions \
ra/arm/CMSIS-DSP/Source/CommonTables \
ra/arm/CMSIS-DSP/Source/ComplexMathFunctions \
ra/arm/CMSIS-DSP/Source/FastMathFunctions \
ra/arm/CMSIS-DSP/Source/TransformFunctions \
ra/arm/CMSIS-NN/Source/ActivationFunctions \
ra/arm/CMSIS-NN/Source/BasicMathFunctions \
ra/arm/CMSIS-NN/Source/ConcatenationFunctions \
ra/arm/CMSIS-NN/Source/ConvolutionFunctions \
ra/arm/CMSIS-NN/Source/FullyConnectedFunctions \
ra/arm/CMSIS-NN/Source/LSTMFunctions \
ra/arm/CMSIS-NN/Source/NNSupportFunctions \
ra/arm/CMSIS-NN/Source/PadFunctions \
ra/arm/CMSIS-NN/Source/PoolingFunctions \
ra/arm/CMSIS-NN/Source/ReshapeFunctions \
ra/arm/CMSIS-NN/Source/SVDFunctions \
ra/arm/CMSIS-NN/Source/SoftmaxFunctions \
ra/arm/CMSIS-NN/Source/TransposeFunctions \
ra/arm/CMSIS-View/EventRecorder/Source \
ra/board/ra8p1_ek \
ra/fsp/src/bsp/cmsis/Device/RENESAS/Source \
ra/fsp/src/bsp/mcu/all \
ra/fsp/src/bsp/mcu/ra8p1 \
ra/fsp/src/r_dmac \
ra/fsp/src/r_ioport \
ra/fsp/src/r_pdm \
ra/fsp/src/r_sci_b_uart \
ra/fsp/src/rm_ethosu \
ra/npu/ethos-u-core-driver/src \
ra_gen \
src/SEGGER_RTT \
src \
src/ruhmi_model \

