/***********************************************************************************************************************
 * File Name    : hal_entry.c
 * Description  : Contains data structures and functions used in hal_entry.c.
 **********************************************************************************************************************/
/***********************************************************************************************************************
* Copyright (c) Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
***********************************************************************************************************************/

#include "pdm_ep.h"
#include "uart_dfplayer.h"
#include "uart_raspi.h"
#include "uart_tangnano.h"
//#include "audio_preprocessing.h"
//#include "pmu_ethosu.h"


FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);
FSP_CPP_FOOTER

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    APP_PRINT("=== Initialize devices in hal_entry ===\n");

    APP_PRINT("Init UART for DFPlayer\n");
    uart_dfplayer_init();

    APP_PRINT("Init UART for Raspi\n");
    uart_raspi_init();

    APP_PRINT("Init UART for Tang Nano\n");
    uart_tangnano_init();

    APP_PRINT("Init NPU\n");
    int status = RM_ETHOSU_Open(&g_rm_ethosu0_ctrl, &g_rm_ethosu0_cfg);
    if (status != FSP_SUCCESS) {
        // NPUの起動失敗エラー処理
        APP_PRINT("ERROR: RUHMI ETHOSU open failed (status=%d)\n", status);
    }

    APP_PRINT("Init PDMIF\n");
    pdm_ep_init();

    /* Start mT-Kernel 3.0 */
    void knl_start_mtkernel(void);
    knl_start_mtkernel();

#if BSP_TZ_SECURE_BUILD

    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

#if BSP_TZ_SECURE_BUILD

FSP_CPP_HEADER
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable()
{

}
FSP_CPP_FOOTER

#endif
